[package]
name = "super-markdown"
version = "0.1.0"
authors = ["Grzegorz Maniak <im@grzegorz.ie>"]
readme = "README.md"

[dependencies]
rand = "0.8.5"
uuid = { version = "1.2.2", features = ["v4", "fast-rng", "macro-diagnostics"] }